package town.guitar.community.mapper;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Component;
import town.guitar.community.model.Post;
import town.guitar.community.model.PostExample;

import java.util.List;

@Component
public interface PostExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Wed Mar 04 02:45:28 GMT+08:00 2020
     */
    long countByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Wed Mar 04 02:45:28 GMT+08:00 2020
     */
    int deleteByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Wed Mar 04 02:45:28 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Wed Mar 04 02:45:28 GMT+08:00 2020
     */
    int insert(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Wed Mar 04 02:45:28 GMT+08:00 2020
     */
    int insertSelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Wed Mar 04 02:45:28 GMT+08:00 2020
     */
    List<Post> selectByExampleWithBLOBsWithRowbounds(PostExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Wed Mar 04 02:45:28 GMT+08:00 2020
     */
    List<Post> selectByExampleWithBLOBs(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Wed Mar 04 02:45:28 GMT+08:00 2020
     */
    List<Post> selectByExampleWithRowbounds(PostExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Wed Mar 04 02:45:28 GMT+08:00 2020
     */
    List<Post> selectByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Wed Mar 04 02:45:28 GMT+08:00 2020
     */
    Post selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Wed Mar 04 02:45:28 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Wed Mar 04 02:45:28 GMT+08:00 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Wed Mar 04 02:45:28 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Wed Mar 04 02:45:28 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Wed Mar 04 02:45:28 GMT+08:00 2020
     */
    int updateByPrimaryKeyWithBLOBs(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Wed Mar 04 02:45:28 GMT+08:00 2020
     */
    int updateByPrimaryKey(Post record);
}